apiVersion: apps/v1
kind: Deployment
metadata:
  name: jyp-deployment
  namespace: fastapi-tutorial
  labels:
    app: jyp
spec:
  replicas: 8
  selector:
    matchLabels:
      app: jyp-app
  template:
    metadata:
      labels:
        app: jyp-app
    spec:
      initContainers:
        - name: init-postgres-service
          image: postgres:10.17
          command: ['sh', '-c',
          'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432;
          do echo waiting for database; sleep 2; done;']

      containers:
        - image: nazzang49/jyp:latest
          imagePullPolicy: Always
          name: jyp-container
          envFrom:
          - secretRef:
              name: jyp-secret
          ports:
            - containerPort: 5000
              name: fastapi
          readinessProbe:
            httpGet:
              port: 5000
              path: /docs
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              port: 5000
              path: /docs
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"